Console.WriteLine("...Minhas frutas favoritas...");
Console.WriteLine("");
Console.WriteLine("1 - Mexerica");
Console.WriteLine("");
Console.WriteLine("2 - Maçã Verde");
Console.WriteLine("");
Console.WriteLine("3 - Laranja");
Console.WriteLine("");
Console.WriteLine("4 - Banana");
Console.WriteLine("");
Console.WriteLine("5 - Manga");
